-- MySQL Script generated by MySQL Workbench
-- Mon Oct 17 18:12:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema anzuelo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema anzuelo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `anzuelo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `anzuelo` ;

-- -----------------------------------------------------
-- Table `anzuelo`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anzuelo`.`categoria` (
  `idcategoria` INT NOT NULL,
  `categoria_nombre` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '			';


-- -----------------------------------------------------
-- Table `anzuelo`.`orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anzuelo`.`orden` (
  `idorden` INT NOT NULL,
  `opcion_envio` VARCHAR(1500) NULL DEFAULT NULL,
  `envio_direccion` VARCHAR(2000) NULL DEFAULT NULL,
  `telefono` INT NULL DEFAULT NULL,
  `email` VARCHAR(150) NULL DEFAULT NULL,
  `estado` VARCHAR(500) NULL DEFAULT NULL,
  `direccion` VARCHAR(500) NULL DEFAULT NULL,
  `pais` VARCHAR(150) NULL DEFAULT NULL,
  `provincia` VARCHAR(500) NULL DEFAULT NULL,
  `ciudad` VARCHAR(500) NULL DEFAULT NULL,
  `ordencol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idorden`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '		';


-- -----------------------------------------------------
-- Table `anzuelo`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anzuelo`.`usuario` (
  `idusuario` INT NOT NULL,
  `password` VARCHAR(12) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `orden_idorden` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `orden_idorden`),
  INDEX `fk_usuario_orden1_idx` (`orden_idorden` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_orden1`
    FOREIGN KEY (`orden_idorden`)
    REFERENCES `anzuelo`.`orden` (`idorden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '	';


-- -----------------------------------------------------
-- Table `anzuelo`.`noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anzuelo`.`noticia` (
  `idnoticia` INT NOT NULL,
  `titulo_noticia` VARCHAR(150) NULL DEFAULT NULL,
  `subtitulo_noticia` VARCHAR(1000) NULL DEFAULT NULL,
  `imagen_noticia` VARCHAR(150) NULL DEFAULT NULL,
  `pie_imagen_noticia` VARCHAR(200) NULL DEFAULT NULL,
  `cuerpo_noticia` VARCHAR(5000) NULL DEFAULT NULL,
  `usuario_idusuario` INT NOT NULL,
  `usuario_orden_idorden` INT NOT NULL,
  PRIMARY KEY (`idnoticia`, `usuario_idusuario`, `usuario_orden_idorden`),
  INDEX `fk_noticia_usuario1_idx` (`usuario_idusuario` ASC, `usuario_orden_idorden` ASC) VISIBLE,
  CONSTRAINT `fk_noticia_usuario1`
    FOREIGN KEY (`usuario_idusuario` , `usuario_orden_idorden`)
    REFERENCES `anzuelo`.`usuario` (`idusuario` , `orden_idorden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `anzuelo`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anzuelo`.`persona` (
  `idpersona` INT NOT NULL,
  `nombre` VARCHAR(75) NULL DEFAULT NULL,
  `apellido` VARCHAR(75) NULL DEFAULT NULL,
  `fecha_de_nacimiento` DATE NULL DEFAULT NULL,
  `direcion` VARCHAR(250) NULL DEFAULT NULL,
  `usuario_idusuario` INT NOT NULL,
  `usuario_orden_idorden` INT NOT NULL,
  PRIMARY KEY (`idpersona`, `usuario_idusuario`, `usuario_orden_idorden`),
  INDEX `fk_persona_usuario1_idx` (`usuario_idusuario` ASC, `usuario_orden_idorden` ASC) VISIBLE,
  CONSTRAINT `fk_persona_usuario1`
    FOREIGN KEY (`usuario_idusuario` , `usuario_orden_idorden`)
    REFERENCES `anzuelo`.`usuario` (`idusuario` , `orden_idorden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `anzuelo`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anzuelo`.`post` (
  `idPost` INT NOT NULL,
  `titulo_foro` VARCHAR(200) NULL DEFAULT NULL,
  `cuerpo_foro` VARCHAR(1500) NULL DEFAULT NULL,
  `usuario_idusuario` INT NOT NULL,
  `usuario_orden_idorden` INT NOT NULL,
  PRIMARY KEY (`idPost`, `usuario_idusuario`, `usuario_orden_idorden`),
  INDEX `fk_post_usuario1_idx` (`usuario_idusuario` ASC, `usuario_orden_idorden` ASC) VISIBLE,
  CONSTRAINT `fk_post_usuario1`
    FOREIGN KEY (`usuario_idusuario` , `usuario_orden_idorden`)
    REFERENCES `anzuelo`.`usuario` (`idusuario` , `orden_idorden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '					';


-- -----------------------------------------------------
-- Table `anzuelo`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anzuelo`.`producto` (
  `idproducto` INT NOT NULL,
  `descripcion` VARCHAR(5000) NULL DEFAULT NULL,
  `precio_producto` INT NULL DEFAULT NULL,
  `nombre_producto` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `anzuelo`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anzuelo`.`rol` (
  `idrol` INT NOT NULL,
  `rol_nombre` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '		';


-- -----------------------------------------------------
-- Table `anzuelo`.`producto_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anzuelo`.`producto_has_usuario` (
  `producto_idproducto` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`producto_idproducto`, `usuario_idusuario`),
  INDEX `fk_producto_has_usuario_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_producto_has_usuario_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_producto_has_usuario_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `anzuelo`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_has_usuario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `anzuelo`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `anzuelo`.`orden_has_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anzuelo`.`orden_has_producto` (
  `orden_idorden` INT NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`orden_idorden`, `producto_idproducto`),
  INDEX `fk_orden_has_producto_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  INDEX `fk_orden_has_producto_orden1_idx` (`orden_idorden` ASC) VISIBLE,
  CONSTRAINT `fk_orden_has_producto_orden1`
    FOREIGN KEY (`orden_idorden`)
    REFERENCES `anzuelo`.`orden` (`idorden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_has_producto_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `anzuelo`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `anzuelo`.`rol_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anzuelo`.`rol_has_usuario` (
  `rol_idrol` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `usuario_orden_idorden` INT NOT NULL,
  PRIMARY KEY (`rol_idrol`, `usuario_idusuario`, `usuario_orden_idorden`),
  INDEX `fk_rol_has_usuario_usuario1_idx` (`usuario_idusuario` ASC, `usuario_orden_idorden` ASC) VISIBLE,
  INDEX `fk_rol_has_usuario_rol1_idx` (`rol_idrol` ASC) VISIBLE,
  CONSTRAINT `fk_rol_has_usuario_rol1`
    FOREIGN KEY (`rol_idrol`)
    REFERENCES `anzuelo`.`rol` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rol_has_usuario_usuario1`
    FOREIGN KEY (`usuario_idusuario` , `usuario_orden_idorden`)
    REFERENCES `anzuelo`.`usuario` (`idusuario` , `orden_idorden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `anzuelo`.`categoria_has_producto1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anzuelo`.`categoria_has_producto1` (
  `categoria_idcategoria` INT NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`categoria_idcategoria`, `producto_idproducto`),
  INDEX `fk_categoria_has_producto1_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  INDEX `fk_categoria_has_producto1_categoria1_idx` (`categoria_idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_has_producto1_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `anzuelo`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categoria_has_producto1_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `anzuelo`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
